# Generated by Django 4.2.4 on 2025-04-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on_hold', 'On Hold')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('management', 'Management'), ('teamlead', 'Team Lead'), ('staff', 'Staff')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('assigned_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='staff.staff_profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='staff.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_projects', to='staff.staff_profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_staff',
            field=models.ManyToManyField(related_name='staff_projects', to='staff.staff_profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_team_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_projects', to='staff.staff_profile'),
        ),
    ]
